import { ArrowUpRight, Briefcase, MapPin, Phone } from 'lucide-react';
import { Project } from '@/types';

interface Props { projects: Project[]; urgentProjects: Project[]; isEditor: boolean; onSelect: (project: Project) => void; onViewAll: () => void; }
export function ClientProjectsDeadlines({ projects, urgentProjects, isEditor, onSelect, onViewAll }: Props) {
  return <section className="dashboard-panel dashboard-panel--projects flex flex-col overflow-hidden rounded-2xl border border-[#dfd9d2] border-t-3 border-t-[#b99a5e] bg-white shadow-[0_10px_30px_rgba(48,44,46,.07)]">
    <div className="flex items-center justify-between border-b border-[#ece6e1] bg-linear-to-r from-[#f8f1f3] via-[#fbf7f1] to-white p-4 sm:p-5"><h3 className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-wide text-slate-800"><Briefcase className="size-4 text-rose-700" />Client Projects & Delivery Deadlines</h3><button onClick={onViewAll} className="flex items-center gap-0.5 text-xs font-bold uppercase tracking-wider text-rose-700 hover:text-rose-900">View All ({projects.length})<ArrowUpRight className="size-3.5" /></button></div>
    <div className="space-y-2.5 p-4">{urgentProjects.map((project) => <div key={project.id} onClick={() => onSelect(project)} className="dashboard-row group flex cursor-pointer flex-col justify-between gap-3 rounded-xl border border-[#e6ded8] bg-[#faf8f6] p-3 transition hover:border-rose-300 sm:flex-row sm:items-center"><div className="space-y-0.5"><div className="flex items-center gap-2"><h4 className="text-sm font-bold text-slate-900 transition group-hover:text-rose-700">{project.clientWeddingTitle}</h4><span className={`rounded border px-2 py-0.5 text-xs font-bold uppercase tracking-wider ${project.status === 'urgent' ? 'border-red-200 bg-red-100 text-red-700' : project.status === 'ready_to_deliver' ? 'border-green-200 bg-green-100 text-green-700' : 'border-rose-200 bg-rose-100 text-rose-800'}`}>{(project.status || '').replace(/_/g, ' ')}</span></div><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="flex items-center gap-1"><MapPin className="size-3 text-slate-400" />{project.venueLocation}</span><span>•</span><span className="flex items-center gap-1"><Phone className="size-3 text-slate-400" />{project.clientContactMobile}</span><span>•</span><span className="font-semibold text-rose-700">{project.primaryServiceType}</span></div></div><div className="flex items-center gap-3 self-end text-right sm:self-auto">{!isEditor && <div><div className="text-xs font-semibold text-slate-600">Budget: ₹{project.totalBudget.toLocaleString('en-IN')}</div><div className={`text-xs font-bold ${project.balanceDue > 0 ? 'text-red-600' : 'text-green-600'}`}>{project.balanceDue > 0 ? `Due: ₹${project.balanceDue.toLocaleString('en-IN')}` : 'Paid in Full'}</div></div>}<div className="flex size-7 items-center justify-center rounded border border-slate-200 bg-white text-slate-400 transition group-hover:bg-rose-700 group-hover:text-white"><ArrowUpRight className="size-3.5" /></div></div></div>)}</div>
  </section>;
}
