'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Bell, Check, KeyRound, Settings, ShieldCheck, UserCog, X } from 'lucide-react';
import { settingsApi, type ModuleAccessRequest, type SettingsWorkspace } from '@/lib/api/settings';
import { useToast } from '@/components/common';
import { Badge, BTN_DANGER, BTN_GHOST, BTN_PRIMARY, CARD, EmptyState, FIELD, LABEL, Modal, ModalHero, SectionCard } from '@/features/team/components/TeamUiKit';

const statusClass = (s: ModuleAccessRequest['status']) => s === 'APPROVED' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : s === 'REJECTED' ? 'border-red-200 bg-red-50 text-red-700' : 'border-amber-200 bg-amber-50 text-amber-800';
const date = (v: string) => new Date(v).toLocaleDateString();
type SaveFn = (action: () => Promise<unknown>, message: string, skipReload?: boolean) => Promise<void>;
type Viewer = { id: string; fullName: string; email: string; permissions: string[]; organization: { name: string; timezone: string; currency: string } };
const immediateWorkspace = (viewer: Viewer): SettingsWorkspace => ({
  viewer: { id: viewer.id, fullName: viewer.fullName, email: viewer.email, isAdmin: viewer.permissions.includes('SETTING_UPDATE') || viewer.permissions.includes('ORG_UPDATE') },
  organization: viewer.organization, notifications: {}, security: {},
  grantedModules: [...new Set(viewer.permissions.map((key) => key.split('_')[0]))].map((key) => ({ key, label: key.replace(/_/g, ' ') })), availableModules: [], requests: [],
});

export function SettingsManager({ viewer }: { viewer?: Viewer }) {
  const { showToast } = useToast(); const [data, setData] = useState<SettingsWorkspace | null>(() => viewer ? immediateWorkspace(viewer) : null); const [loading, setLoading] = useState(!viewer); const [error, setError] = useState('');
  const [requesting, setRequesting] = useState<SettingsWorkspace['availableModules'][number] | null>(null); const [reviewing, setReviewing] = useState<ModuleAccessRequest | null>(null); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await settingsApi.workspace()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load settings.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async (action: () => Promise<unknown>, message: string, skipReload = false) => { setSaving(true); try { await action(); showToast(message); if (!skipReload) await load(); } catch (e) { showToast(e instanceof Error ? e.message : 'Could not save changes.', { variant: 'error' }); } finally { setSaving(false); } };
  // Keep the canvas clean while GET /settings/workspace responds.
  if (loading && !data) return null;
  if (error || !data) return <div className={CARD}><EmptyState icon={Settings} title="Settings unavailable" message={error} action={<button className={BTN_PRIMARY} onClick={() => void load()}>Retry</button>} /></div>;
  const pending = new Set(data.requests.filter(r => r.status === 'PENDING').map(r => r.moduleKey));
  return <div className="space-y-6 pb-8">
    <section className="rounded-3xl border border-[#ddc89c]/35 bg-[linear-gradient(125deg,#704758,#55333f_50%,#38262d)] p-5 text-white shadow-xl sm:p-7"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#f0dce3]">Workspace</p><h1 className="mt-2 text-3xl font-black">Settings</h1><p className="mt-2 text-sm text-[#eadfe2]">Manage your profile, preferences and access from one place.</p></section>
    <Profile data={data} admin={data.viewer.isAdmin} save={save} />
    {data.viewer.isAdmin && <Organization data={data} save={save} />}
    <Preferences data={data} save={save} />
    {data.viewer.isAdmin ? <AdminRequests data={data} reviewing={reviewing} setReviewing={setReviewing} /> : <EmployeeAccess data={data} pending={pending} setRequesting={setRequesting} />}
    {data.viewer.isAdmin && <SectionCard title="User & Employee" subtitle="Roles and employee access are managed in the existing Roles & Permissions desk." icon={UserCog}><a href="/roles-permissions" className={BTN_GHOST}>Open Roles & Permissions</a></SectionCard>}
    <RequestModal module={requesting} reason={reason} setReason={setReason} saving={saving} close={() => { setRequesting(null); setReason(''); }} submit={() => void save(async () => { if (!requesting || !reason.trim()) throw new Error('Please enter a reason.'); await settingsApi.requestModule({ moduleKey: requesting.key, reason }); }, 'Access request submitted.')} />
    <ReviewModal request={reviewing} saving={saving} close={() => setReviewing(null)} submit={(status) => void save(async () => { if (!reviewing) return; await settingsApi.reviewModuleRequest(reviewing.id, { status, reviewReason: reason }); setReviewing(null); setReason(''); }, `Request ${status.toLowerCase()}.`)} reason={reason} setReason={setReason} />
  </div>;
}

function Profile({ data, admin, save }: { data: SettingsWorkspace; admin: boolean; save: (a: () => Promise<unknown>, m: string) => Promise<void> }) { const [name, setName] = useState(data.viewer.fullName); const [phone, setPhone] = useState(data.viewer.phone || ''); return <SectionCard title="My Profile" subtitle="Your account details" icon={UserCog} actions={<button className={BTN_PRIMARY} onClick={() => void save(() => settingsApi.updateProfile({ fullName: name, phone }), 'Profile updated.')}>Save profile</button>}><div className="grid gap-3 sm:grid-cols-2"><Field label="Name" value={name} set={setName} /><Field label="Email" value={data.viewer.email} set={() => {}} disabled /><Field label="Phone" value={phone} set={setPhone} /></div>{admin && <p className="mt-3 text-xs font-medium text-slate-500">Organization settings are available below for administrators.</p>}</SectionCard> }
function Organization({ data, save }: { data: SettingsWorkspace; save: (a: () => Promise<unknown>, m: string) => Promise<void> }) { const o = data.organization || { name: '', timezone: '', currency: '', dateFormat: '' }; const [form, setForm] = useState(o); return <SectionCard title="General" subtitle="Studio identity and regional preferences" icon={Settings} actions={<button className={BTN_PRIMARY} onClick={() => void save(() => settingsApi.updateOrganization(form), 'Organization settings updated.')}>Save general</button>}><div className="grid gap-3 sm:grid-cols-2"><Field label="Organization name" value={form.name} set={v => setForm({ ...form, name: v })} /><Field label="Contact email" value={form.contactEmail || ''} set={v => setForm({ ...form, contactEmail: v })} /><Field label="Timezone" value={form.timezone || ''} set={v => setForm({ ...form, timezone: v })} /><Field label="Currency" value={form.currency || ''} set={v => setForm({ ...form, currency: v })} /><Field label="Date format" value={form.dateFormat || ''} set={v => setForm({ ...form, dateFormat: v })} /></div></SectionCard> }
function Preferences({ data, save }: { data: SettingsWorkspace; save: SaveFn }) { const [notifications, setNotifications] = useState(data.notifications); return <><SectionCard title="Notifications" subtitle="Choose what you want to receive" icon={Bell} actions={<button className={BTN_PRIMARY} onClick={() => void save(() => settingsApi.updatePreferences({ notifications }), 'Notification preferences updated.')}>Save preferences</button>}><div className="space-y-2">{Object.entries(notifications).map(([key, on]) => <label key={key} className="flex items-center justify-between rounded-xl border border-[#eee7e2] p-3 text-sm font-bold text-slate-700"><span>{key.replace(/([A-Z])/g, ' $1')}</span><input type="checkbox" checked={on} onChange={e => setNotifications({ ...notifications, [key]: e.target.checked })} /></label>)}</div></SectionCard><SectionCard title="Account & Security" subtitle="Change your password and session preferences" icon={KeyRound}><Password save={save} /></SectionCard></> }
const passwordPolicyError = (value: string) => value.length < 10 ? 'New password must be at least 10 characters.' : !/[a-z]/.test(value) ? 'New password must contain a lowercase letter.' : !/[A-Z]/.test(value) ? 'New password must contain an uppercase letter.' : !/\d/.test(value) ? 'New password must contain a digit.' : null;
function Password({ save }: { save: SaveFn }) { const [currentPassword, setCurrent] = useState(''); const [newPassword, setNew] = useState(''); return <div className="grid gap-3 sm:grid-cols-2"><Field label="Current password" value={currentPassword} set={setCurrent} type="password" /><Field label="New password" value={newPassword} set={setNew} type="password" /><button className={`${BTN_GHOST} w-fit`} onClick={() => void save(async () => { const invalid = passwordPolicyError(newPassword); if (invalid) throw new Error(invalid); await settingsApi.changePassword({ currentPassword, newPassword }); setCurrent(''); setNew(''); }, 'Password changed. Please sign in again with your new password.', true)}>Change password</button></div> }
function EmployeeAccess({ data, pending, setRequesting }: { data: SettingsWorkspace; pending: Set<string>; setRequesting: (m: SettingsWorkspace['availableModules'][number]) => void }) { return <SectionCard title="My Module Access" subtitle="Your granted access and modules you can request" icon={ShieldCheck}><div className="grid gap-5 md:grid-cols-2"><List title="Access granted" items={data.grantedModules} /><div><p className="mb-2 text-xs font-extrabold uppercase tracking-wider text-slate-500">Available to request</p>{data.availableModules.length ? data.availableModules.map(m => <div className="mb-2 flex items-center justify-between rounded-xl border border-[#eee7e2] p-3" key={m.key}><div><p className="text-sm font-extrabold">{m.label}</p><p className="text-xs text-slate-500">{m.description}</p></div>{pending.has(m.key) ? <Badge className={statusClass('PENDING')}>Pending</Badge> : <button className={BTN_GHOST} onClick={() => setRequesting(m)}>Request</button>}</div>) : <EmptyState title="Nothing to request" message="All available modules are already assigned." />}</div></div><RequestStatus requests={data.requests} /></SectionCard> }
function AdminRequests({ data, setReviewing }: { data: SettingsWorkspace; reviewing: ModuleAccessRequest | null; setReviewing: (r: ModuleAccessRequest) => void }) { return <SectionCard title="Module Access Requests" subtitle="Review employee requests for additional modules" icon={ShieldCheck}>{data.requests.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-[10px] uppercase text-slate-500"><tr><th>Name</th><th>Module</th><th>Reason</th><th>Date</th><th>Status</th><th /></tr></thead><tbody>{data.requests.map(r => <tr className="border-t border-[#eee7e2]" key={r.id}><td className="py-3 font-bold">{r.employeeName}<small className="block font-normal text-slate-500">{r.employeeEmail}</small></td><td>{r.moduleLabel}</td><td className="max-w-48 truncate">{r.reason}</td><td>{date(r.createdAt)}</td><td><Badge className={statusClass(r.status)}>{r.status}</Badge></td><td><button className={BTN_GHOST} onClick={() => setReviewing(r)}>View</button></td></tr>)}</tbody></table></div> : <EmptyState icon={ShieldCheck} title="No requests yet" message="Employee access requests will appear here." />}</SectionCard> }
function RequestStatus({ requests }: { requests: ModuleAccessRequest[] }) { return <div className="mt-5"><p className="mb-2 text-xs font-extrabold uppercase tracking-wider text-slate-500">My requests</p>{requests.length ? requests.map(r => <div className="mb-2 rounded-xl border border-[#eee7e2] p-3 text-sm" key={r.id}><b>{r.moduleLabel}</b> <Badge className={statusClass(r.status)}>{r.status}</Badge><span className="ml-2 text-xs text-slate-500">{date(r.createdAt)}</span>{r.reviewReason && <p className="mt-1 text-xs text-slate-500">{r.reviewerName || 'Reviewer'}: {r.reviewReason}</p>}</div>) : <EmptyState title="No requests yet" />}</div> }
function List({ title, items }: { title: string; items: SettingsWorkspace['grantedModules'] }) { return <div><p className="mb-2 text-xs font-extrabold uppercase tracking-wider text-slate-500">{title}</p>{items.length ? items.map(m => <div className="mb-2 rounded-xl border border-emerald-100 bg-emerald-50/40 p-3" key={m.key}><p className="text-sm font-extrabold">{m.label}</p><p className="text-xs text-slate-500">{m.description}</p></div>) : <EmptyState title="No access granted" message="Approved modules will appear here." />}</div> }
function Field({ label, value, set, disabled, type = 'text' }: { label: string; value: string; set: (v: string) => void; disabled?: boolean; type?: string }) { return <label><span className={LABEL}>{label}</span><input className={FIELD} type={type} value={value} disabled={disabled} onChange={e => set(e.target.value)} /></label> }
function RequestModal({ module, reason, setReason, saving, close, submit }: { module: SettingsWorkspace['availableModules'][number] | null; reason: string; setReason: (v: string) => void; saving: boolean; close: () => void; submit: () => void }) { return <Modal isOpen={!!module} onClose={close} labelledBy="request-title"><ModalHero icon={ShieldCheck} eyebrow="Access request" title={`Request ${module?.label || ''}`} onClose={close} labelledBy="request-title" /><div className="space-y-3 p-5"><label><span className={LABEL}>Why do you need this module? *</span><textarea className={FIELD} value={reason} onChange={e => setReason(e.target.value)} rows={4} /></label><button disabled={saving || !reason.trim()} className={BTN_PRIMARY} onClick={submit}>Submit request</button></div></Modal> }
function ReviewModal({ request, saving, close, submit, reason, setReason }: { request: ModuleAccessRequest | null; saving: boolean; close: () => void; submit: (s: 'APPROVED' | 'REJECTED') => void; reason: string; setReason: (v: string) => void }) { const [confirm, setConfirm] = useState<'APPROVED' | 'REJECTED' | null>(null); useEffect(() => setConfirm(null), [request?.id]); return <Modal isOpen={!!request} onClose={close} labelledBy="review-title"><ModalHero icon={ShieldCheck} eyebrow={confirm ? 'Confirm decision' : 'Access request'} title={confirm ? `${confirm === 'APPROVED' ? 'Approve' : 'Reject'} this request?` : request?.moduleLabel || ''} onClose={close} labelledBy="review-title" /><div className="space-y-3 p-5 text-sm">{confirm ? <><p>This will notify {request?.employeeName} and update their access-request status.</p><div className="flex gap-2"><button className={BTN_GHOST} onClick={() => setConfirm(null)}>Back</button><button disabled={saving} className={confirm === 'APPROVED' ? BTN_PRIMARY : BTN_DANGER} onClick={() => submit(confirm)}>{confirm === 'APPROVED' ? 'Yes, approve' : 'Yes, reject'}</button></div></> : <><p><b>{request?.employeeName}</b> · {request?.employeeEmail}</p><p className="rounded-xl bg-[#fbfaf8] p-3">{request?.reason}</p>{request?.status === 'PENDING' && <><label><span className={LABEL}>Review note (optional)</span><textarea className={FIELD} value={reason} onChange={e => setReason(e.target.value)} rows={3} /></label><div className="flex gap-2"><button disabled={saving} className={BTN_PRIMARY} onClick={() => setConfirm('APPROVED')}><Check className="size-4" /> Approve</button><button disabled={saving} className={BTN_DANGER} onClick={() => setConfirm('REJECTED')}><X className="size-4" /> Reject</button></div></>}</>}</div></Modal> }
